config/routes.rb
FreedomShop::Application.routes.draw do

  resources :people

  resources :sessions

  get "users/new"
  resources :media

  get "logout" => 'sessions#destroy'

  get "dashboard/index"
  root to: "media#index"
    
end

app/models/medium.rb
class Medium < ActiveRecord::Base
  before_destroy :delete_file
  def url
    "/uploads/#{filename}" if filename
  end

  private
  def delete_file
    File.delete Rails.root.join("public", "uploads", filename) if filename
  end
end

app/models/person.rb
require 'digest/sha2'

class Person < ActiveRecord::Base
  attr_reader :password

  ENCRYPT = Digest::SHA256

  has_many :sessions, :dependent => :destroy

  validates_uniqueness_of :name, :message => "is already used by another person"
  validates_format_of :password, :with => /\A([\x20-\x7E]){4,16}\z/,
    :message => "must be 4 to 16 characters",
    :unless => :password_is_not_being_updated?

  validates_confirmation_of :password

  before_save :scrub_name
  after_save :flush_passwords

  def self.find_by_name_and_password(name, password)
    person = self.find_by_name(name)
    if person and person.encrypted_password = ENCRYPT.hexdigest(password + person.salt)
      return person
    end
  end

  def password=(password)
    @password = password
    unless password_is_not_being_updated?
      self.salt, self.encrypted_password = Person.hash(password)
    end
  end

  def self.hash(password)
      salt = [Array.new(9){rand(256).chr}.join].pack('m').chomp
      encrypted_password = ENCRYPT.hexdigest(password + salt)

      return salt, encrypted_password
  end

  private

  def scrub_name
    self.name.downcase!
  end

  def flush_passwords
    @password = @password_confirmation = nil
  end

  def password_is_not_being_updated?
    self.id and self.password.blank?
  end

end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessor :name, :password, :match

  belongs_to :person
  before_validation :authenticate_person

  validates_presence_of :match,
    :message => 'for your name and password could not be found',
    :unless  => :session_has_been_associated?

  before_save :associate_session_to_person

  private

  def authenticate_person
    unless session_has_been_associated?
      self.match = Person.find_by_name_and_password(self.name, self.password)
    end
  end

  def associate_session_to_person
    self.person_id ||= self.match.id
  end

  def session_has_been_associated?
    self.person_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 

  helper :all

  before_filter :maintain_session_and_user

  protect_from_forgery

  def ensure_login
    unless @user
      flash[:notice] = "Please login to continue"
      redirect_to new_session_path
    end
  end

  def ensure_logout
    if @user
      redirect_to root_url
    end
  end

  private

  def maintain_session_and_user
    if session[:id]
      if @application_session = Session.find_by_id(session[:id])
        @application_session.update_attributes(
          :ip_address => request.remote_addr,
          :path => request.path_info
        )
        @user = @application_session.person
      else
        session[:id] = nil
        redirect_to root_url
      end
    end
  end
    
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :ensure_login
  def index
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_filter :ensure_login, :except => [:show,:index]
  before_action :set_medium, only: [:show, :edit, :update, :destroy]

  # GET /media
  # GET /media.json
  def index
    @media = Medium.all
  end

  # GET /media/1
  # GET /media/1.json
  def show
  end

  # GET /media/new
  def new
    @medium = Medium.new
  end

  # GET /media/1/edit
  def edit
  end

  # POST /media
  # POST /media.json
  def create
    uploaded_io = params[:medium][:picture]

    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    params[:medium][:filename]  = uploaded_io.original_filename
    params[:medium][:extension] = uploaded_io.path

    @medium = Medium.new(medium_params)

    respond_to do |format|
      if @medium.save
        format.html { redirect_to @medium, notice: 'Medium was successfully created.' }
        format.json { render action: 'show', status: :created, location: @medium }
      else
        format.html { render action: 'new' }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media/1
  # PATCH/PUT /media/1.json
  def update
    respond_to do |format|
      if @medium.update(medium_params)
        format.html { redirect_to @medium, notice: 'Medium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.json
  def destroy
    @medium.destroy
    respond_to do |format|
      format.html { redirect_to media_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medium
      @medium = Medium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medium_params
      params.require(:medium).permit(:name, :filename, :extension, :type, :comment)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :ensure_login, :only => [:edit, :update, :destroy]
  before_filter :ensure_logout, :only => [:new, :create]

  def index
    @people = Person.find(:all)
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(parms[:person])
    if @person.save
      @session = @person.session.create
      session[:id] = @session.id
      flash[:notice] = "Welcome #{@person.name}, you are now registered"
      redirect_to root_url
    else
      render :action => 'new'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :ensure_login, :only => :destroy
  before_filter :ensure_logout, :only => [:new, :create]

  def index
    redirect_to new_session_path
  end

  def new
    @session = Session.new
  end

  def create
    @session = Session.new(session_params)
    if @session.save
      session[:id] = @session.id
      flash[:notice] = "Hello #{@session.name}, you are now logged in"
      redirect_to root_url
    else
      render :action => 'new'
    end
  end

  def destroy
    Session.destroy @application_session
    session[:id] = @user = nil
    flash[:notice] = "You are now logged out"
    redirect_to root_url
  end

  private
    def session_params
      params.require(:session).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<% content_for :sidebar do %>
  <li class="nav-divider"></li>
  <li><a href="#"><span class="glyphicon glyphicon-dashboard"></span> Dashboard Home</a></li>
<% end %>

<% content_for :content do %>
  <h1><span class="glyphicon glyphicon-dashboard"></span> Welcome to the DASHBOARD!</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>FreedomShop</title>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/main_nav' %>

<div class="container">
    <div class="grid">
        <div class="col-md-3">
            <ul class="nav nav-stacked">
                <li><a href="#"><span class="glyphicon glyphicon-home"></span> Home</a></li>
                <li class="navbar-heading">Media</li>
                <li><%= link_to(media_path) do %><span class='glyphicon glyphicon-picture'></span> View Media<% end %></li>
                <% if @user %>
                <li><%= link_to(new_medium_path) do %><span class='glyphicon glyphicon-plus-sign'></span> Create Media<% end %></li>
                <% end %>
                <%= content_for?(:sidebar) ? yield(:sidebar) : '' %>
            </ul>
        </div>
        <div class="col-md-9">
            <% if flash[:notice] %>
                <div class="alert alert-danger">
                <%= flash[:notice] %>
            </div>
        <% end %>
            <%= content_for?(:content) ? yield(:content) : yield %>
        </div>
    </div>
</div>

</body>
</html>

app/views/media/_form.html.erb
<%= form_for(@medium) do |f| %>
  <% if @medium.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@medium.errors.count, "error") %> prohibited this medium from being saved:</h2>

      <ul>
      <% @medium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div><%= image_tag @medium.url, :style => "max-width:100%;" if @medium.url %></div>

<table class="table table-bordered">
<tbody>
  <tr>
    <th style="text-align:right; width: 200px;padding-right:10px;"><%= f.label "File" %></th>
    <td><%= f.file_field :picture, class: "form-control" %></td>
  </tr>
  <tr>
    <th style="text-align:right; width: 200px;padding-right:10px;"><%= f.label :name %></th>
    <td><%= f.text_field :name, class: "form-control" %></td>
  </tr>
  <tr>
    <th style="text-align:right; width: 200px;padding-right:10px;"><%= f.label :extension %></th>
    <td><%= f.text_field :extension, class: "form-control" %></td>
  </tr>
  <tr>
    <th style="text-align:right; width: 200px;padding-right:10px;"><%= f.label :comment %></th>
    <td><%= f.text_area :comment, class: "form-control"  %></td>
  </tr>
  <tr>
    <th></th>
    <td><%= f.submit "Create", class: "btn btn-primary" %></td>
  </tr>
</tbody>
</table>
<% end %>

app/views/media/edit.html.erb
<h1>Editing medium</h1>

<%= render 'form' %>

<%= link_to 'Show', @medium %> |
<%= link_to 'Back', media_path %>

app/views/media/index.html.erb
<h1>Listing media</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th style="width:100px;"><div style="width:100px;"></div></th>
      <th>Name</th>
      <th>Filename</th>
      <th>Extension</th>
      <th>Type</th>
      <th>Comment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @media.each do |medium| %>
      <tr>
        <td><%= image_tag medium.url, :class => "img-thumbnail" if medium.url %></td>
        <td><%= medium.name %></td>
        <td><%= medium.filename %></td>
        <td><%= truncate medium.extension, :length => 30 %></td>
        <td><%= medium.type %></td>
        <td><%= medium.comment %></td>
        <td><%= link_to 'Show', medium %></td>
        <% if @user %>
        <td><%= link_to 'Edit', edit_medium_path(medium) %></td>
        <td><%= link_to 'Destroy', medium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @user %>
<%= link_to 'New Medium', new_medium_path %>
<% end %>

app/views/media/new.html.erb
<h1>New medium</h1>

<%= render 'form' %>

<%= link_to 'Back', media_path %>

app/views/media/show.html.erb
<%= image_tag @medium.url, :style => "max-width:100%;margin-bottom:20px;" if @medium.url %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @medium.name %>
</p>

<p>
  <strong>Filename:</strong>
  <%= @medium.filename %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @medium.extension %>
</p>

<p>
  <strong>Type:</strong>
  <%= @medium.type %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @medium.comment %>
</p>

<% if @user %>
<%= link_to 'Edit', edit_medium_path(@medium) %> |
<% end %>
<%= link_to 'Back', media_path %>

app/views/shared/_main_nav.html.erb
<nav class="nav navbar navbar-default navbar-static-top">
  <div class="container">

    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
    </ul>

    <% if @user %>
    <form action="" class="navbar-form navbar-left">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>

    <ul class="nav navbar-nav navbar-right">

      <li class="dropdown">
        <a href="#" data-toggle="dropdown">
          <span class="glyphicon glyphicon-cog"></span>
          Profile <b class="caret"></b>
        </a>

        <ul class="dropdown-menu">
          <li class="dropdown-header">Actions</li>
          <li class="divider"></li>
          <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        </ul>
      </li>

    </ul>
    <% else %>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to(new_session_path) do %><span class="glyphicon glyphicon-log-in"></span> Login<% end %></li>
        </ul>
    <% end %>

  </div>
</nav>